/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/cerrado/jaguar.glb -t -o ./src/components/cerrado/jaguar.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import jaguarGlb from "@models/cerrado/jaguar.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpzdkekwb0ply: THREE.Mesh;
  };
  materials: object;
};

export function ModelJaguar(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(jaguarGlb) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpzdkekwb0ply.geometry}
        material={nodes.tmpzdkekwb0ply.material}
      />
    </group>
  );
}

useGLTF.preload(jaguarGlb);
