/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/pomp.glb -t -o ./src/components/caatinga/model-pomp.tsx 
*/

import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import pompGlb from "@models/caatinga/pomp.glb";

type GLTFResult = GLTF & {
  nodes: {
    tmp77pr53_oply: THREE.Mesh;
  };
  materials: object;
};

export function ModelPomp(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(pompGlb) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmp77pr53_oply.geometry}
        material={nodes.tmp77pr53_oply.material}
      />
    </group>
  );
}

useGLTF.preload(pompGlb);
