/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/pomp.glb -t -o ./src/components/caatinga/model-pomp.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    tmp77pr53_oply: THREE.Mesh;
  };
  materials: object;
};

export function ModelPomp(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/pomp.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tmp77pr53_oply.geometry}
        material={nodes.tmp77pr53_oply.material}
      />
    </group>
  );
}

useGLTF.preload("/pomp.glb");
