/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/rock-3.glb -t -o ./src/components/caatinga/model-rock-3.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import rock3Glb from "@models/caatinga/rock-3.glb";

type GLTFResult = GLTF & {
  nodes: {
    Rock_4: THREE.Mesh;
  };
  materials: {
    Atlas: THREE.MeshStandardMaterial;
  };
};

export function ModelRock3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(rock3Glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Rock_4.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload(rock3Glb);
