/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/grass-2.glb -t -o ./src/components/index.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import grass2Glb from "@models/grass-2.glb";

type GLTFResult = GLTF & {
  nodes: {
    group1758196251: THREE.Mesh;
    group303338039: THREE.Mesh;
    group158731365: THREE.Mesh;
    group595482761: THREE.Mesh;
    group1990659664: THREE.Mesh;
    group1238384977: THREE.Mesh;
    group1945249999: THREE.Mesh;
    group1894289659: THREE.Mesh;
    group783281343: THREE.Mesh;
    group266082552: THREE.Mesh;
    group1439209696: THREE.Mesh;
    group1318692651: THREE.Mesh;
  };
  materials: {
    mat9: THREE.MeshStandardMaterial;
  };
};

export function ModelGrass2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(grass2Glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.group1758196251.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group303338039.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group158731365.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group595482761.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group1990659664.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group1238384977.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group1945249999.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group1894289659.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group783281343.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group266082552.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group1439209696.geometry}
        material={materials.mat9}
      />
      <mesh
        geometry={nodes.group1318692651.geometry}
        material={materials.mat9}
      />
    </group>
  );
}

useGLTF.preload(grass2Glb);
