/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/teleporter-base.glb -t 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Props_Base_1: THREE.Mesh;
    Props_Base_2: THREE.Mesh;
    Props_Base_3: THREE.Mesh;
  };
  materials: {
    DarkGrey: THREE.MeshStandardMaterial;
    Main: THREE.MeshStandardMaterial;
    Accent: THREE.MeshStandardMaterial;
  };
};

export function TeleportPlatformModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/teleporter-base.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={170}>
        <mesh
          geometry={nodes.Props_Base_1.geometry}
          material={materials.DarkGrey}
        />
        <mesh
          geometry={nodes.Props_Base_2.geometry}
          material={materials.Main}
        />
        <mesh
          geometry={nodes.Props_Base_3.geometry}
          material={materials.Accent}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/teleporter-base.glb");
