/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ground-sloth.glb -o ./src/components/Maps/components/GroundSloth -t 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    GroundSloth_mesh: THREE.Mesh;
  };
  materials: {
    GroundSloth_mat: THREE.MeshStandardMaterial;
  };
};

export function GroundSloth(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/ground-sloth.glb") as GLTFResult;

  const brightMaterial = new THREE.MeshStandardMaterial({
    color: "#B0A7A6",
    roughness: 0.3,
    metalness: 0,
  });
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.GroundSloth_mesh.geometry}
          material={brightMaterial}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/models/ground-sloth.glb");
