/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tree-1.glb -o teste.tsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import tree1 from "@models/tree-1.glb";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    mat9: THREE.MeshStandardMaterial;
    mat20: THREE.MeshStandardMaterial;
  };
};

export const Tree1 = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(tree1) as GLTFResult;
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes["Node-Mesh"].geometry}
          material={materials.mat9}
        />
        <mesh
          geometry={nodes["Node-Mesh_1"].geometry}
          material={materials.mat20}
        />
      </group>
    </RigidBody>
  );
};

useGLTF.preload(tree1);
