/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/amazonia/alligator.glb -t -o ./src/components/amazonia/index.tsx 
*/

import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import alligatorGlb from "@models/amazonia/alligator.glb";

type GLTFResult = GLTF & {
  nodes: {
    tmpcly6p1ofply: THREE.Mesh;
  };
  materials: object;
};

export function ModelAlligator(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(alligatorGlb) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpcly6p1ofply.geometry}
        material={nodes.tmpcly6p1ofply.material}
      />
    </group>
  );
}

useGLTF.preload(alligatorGlb);
