/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/island-1.glb -o teste.tsx -r public 
*/

import islandModelPath from "@models/island-1.glb";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { useMemo } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    IslandLarge_1: THREE.Mesh;
    IslandLarge_2: THREE.Mesh;
  };
  materials: {
    dirt: THREE.MeshStandardMaterial;
    grass: THREE.MeshStandardMaterial;
  };
};

export const BigIsland = ({
  positionMap,
  color = "#589559",
  ...props
}: JSX.IntrinsicElements["group"] & {
  positionMap: THREE.Vector3;
  color?: string;
}) => {
  const { nodes, materials: originalMaterials } = useGLTF(
    islandModelPath
  ) as GLTFResult;

  const grassMaterial = useMemo(() => {
    const newMaterial = originalMaterials.grass.clone();
    newMaterial.color = new THREE.Color(color);
    newMaterial.roughness = 0.9;
    newMaterial.metalness = 0;
    return newMaterial;
  }, [originalMaterials.grass, color]);

  return (
    <RigidBody type="fixed" position={positionMap} colliders="hull">
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={800}>
          <mesh
            geometry={nodes.IslandLarge_1.geometry}
            material={originalMaterials.dirt} // Assumindo que a cor da terra não muda por instância
          />
          <mesh
            geometry={nodes.IslandLarge_2.geometry}
            material={grassMaterial} // Use o material de grama clonado e personalizado
          />
        </group>
      </group>
    </RigidBody>
  );
};

useGLTF.preload(islandModelPath); // Use a mesma variável de caminho do modelo
