/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/island-1.glb -o teste.tsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import island from "@models/island-1.glb";

type GLTFResult = GLTF & {
  nodes: {
    IslandLarge_1: THREE.Mesh;
    IslandLarge_2: THREE.Mesh;
  };
  materials: {
    dirt: THREE.MeshStandardMaterial;
    grass: THREE.MeshStandardMaterial;
  };
};

export const BigIsland = ({
  positionMap,
  color = "#589559",
  ...props
}: JSX.IntrinsicElements["group"] & {
  positionMap: THREE.Vector3;
  color?: string;
}) => {
  const { nodes, materials } = useGLTF(island) as GLTFResult;

  materials.grass.color.set(color);
  materials.grass.roughness = 0.9;
  materials.grass.metalness = 0;

  return (
    <RigidBody type="fixed" position={positionMap} colliders="hull">
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={800}>
          <mesh
            geometry={nodes.IslandLarge_1.geometry}
            material={materials.dirt}
          />
          <mesh
            geometry={nodes.IslandLarge_2.geometry}
            material={materials.grass}
          />
        </group>
      </group>
    </RigidBody>
  );
};

useGLTF.preload(island);
