/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/island-1.glb -o teste.tsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    IslandLarge_1: THREE.Mesh;
    IslandLarge_2: THREE.Mesh;
  };
  materials: {
    dirt: THREE.MeshStandardMaterial;
    grass: THREE.MeshStandardMaterial;
  };
};

export const BigIsland = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/models/island-1.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={800}>
        <mesh
          geometry={nodes.IslandLarge_1.geometry}
          material={materials.dirt}
        />
        <mesh
          geometry={nodes.IslandLarge_2.geometry}
          material={materials.grass}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/models/island-1.glb");
