/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/question-box.glb -t 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import questionBox from "@models/question-box.glb";

type GLTFResult = GLTF & {
  nodes: {
    mesh1747336890: THREE.Mesh;
    mesh1747336890_1: THREE.Mesh;
    mesh1747336890_2: THREE.Mesh;
    mesh572745584: THREE.Mesh;
    mesh572745584_1: THREE.Mesh;
    mesh1749781905: THREE.Mesh;
    mesh1749781905_1: THREE.Mesh;
    mesh276336442: THREE.Mesh;
    mesh276336442_1: THREE.Mesh;
    mesh1290640350: THREE.Mesh;
    mesh1290640350_1: THREE.Mesh;
  };
  materials: {
    mat20: THREE.MeshStandardMaterial;
    mat13: THREE.MeshStandardMaterial;
    mat12: THREE.MeshStandardMaterial;
    mat22: THREE.MeshStandardMaterial;
    mat21: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(questionBox) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh1747336890.geometry}
        material={materials.mat20}
      />
      <mesh
        geometry={nodes.mesh1747336890_1.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.mesh1747336890_2.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.mesh572745584.geometry}
        material={materials.mat22}
      />
      <mesh
        geometry={nodes.mesh572745584_1.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh1749781905.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh1749781905_1.geometry}
        material={materials.mat22}
      />
      <mesh
        geometry={nodes.mesh276336442.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh276336442_1.geometry}
        material={materials.mat22}
      />
      <mesh
        geometry={nodes.mesh1290640350.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh1290640350_1.geometry}
        material={materials.mat22}
      />
    </group>
  );
}

useGLTF.preload(questionBox);
