/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/pantanal/tuiuiu.glb -t -o ./src/components/pantanal/ModelTuiuiu.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import tuiuiuGLB from "@models/pantanal/tuiuiu.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/useBrightenModel";

type GLTFResult = GLTF & {
  nodes: {
    tmpgfl54ygrply: THREE.Mesh;
  };
  materials: {};
};

export function ModelTuiuiu(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(tuiuiuGLB) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.bird);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpgfl54ygrply.geometry}
        material={nodes.tmpgfl54ygrply.material}
        receiveShadow
        castShadow
      />
    </group>
  );
}

useGLTF.preload(tuiuiuGLB);
