/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/pantanal/snake.glb -t -o ./src/components/pantanal/ModelSnake.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import snakeGLB from "@models/pantanal/snake.glb";

type GLTFResult = GLTF & {
  nodes: {
    tmpjy4y03wfply: THREE.Mesh;
  };
  materials: {};
};

export function ModelSnake(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(snakeGLB) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tmpjy4y03wfply.geometry}
        material={nodes.tmpjy4y03wfply.material}
      />
    </group>
  );
}

useGLTF.preload(snakeGLB);
