/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/pantanal/pink-ipe.glb -t -o ./src/components/pantanal/ModelPinkIpe.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import pinkIpeGLB from "@models/pantanal/pink-ipe.glb";

type GLTFResult = GLTF & {
  nodes: {
    ["??????????_1"]: THREE.Mesh;
    ["??????????_1_1"]: THREE.Mesh;
  };
  materials: {
    ["??????"]: THREE.MeshStandardMaterial;
    ["???????_??????"]: THREE.MeshStandardMaterial;
  };
};

export function ModelPinkIpe(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(pinkIpeGLB) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["??????????_1"].geometry}
        material={materials["??????"]}
      />
      <mesh
        geometry={nodes["??????????_1_1"].geometry}
        material={materials["???????_??????"]}
      />
    </group>
  );
}

useGLTF.preload(pinkIpeGLB);
