/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/pantanal/capybara.glb -t -o ./src/components/ModelCapybara.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import capybaraGLB from "@models/pantanal/capybara.glb";

type GLTFResult = GLTF & {
  nodes: {
    tmpyj5ikku8ply: THREE.Mesh;
  };
  materials: {};
};

export function ModelCapybara(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(capybaraGLB) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tmpyj5ikku8ply.geometry}
        material={nodes.tmpyj5ikku8ply.material}
      />
    </group>
  );
}

useGLTF.preload(capybaraGLB);
