/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/pantanal/alligator.glb -t -o ./src/components/pantanal/ModelAlligator.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import alligatorGLB from "@models/pantanal/alligator.glb";

type GLTFResult = GLTF & {
  nodes: {
    tmp1ac7fcj2ply: THREE.Mesh;
  };
  materials: {};
};

export function ModelAlligator(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(alligatorGLB) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tmp1ac7fcj2ply.geometry}
        material={nodes.tmp1ac7fcj2ply.material}
      />
    </group>
  );
}

useGLTF.preload(alligatorGLB);
