/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/pantanal/alligator.glb -t -o ./src/components/pantanal/ModelAlligator.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import alligatorGLB from "@models/pantanal/alligator.glb";
import {
  useBrightenModel,
  animalBrightenPresets,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmp1ac7fcj2ply: THREE.Mesh;
  };
  materials: {};
};

export function ModelAlligator(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(alligatorGLB) as GLTFResult;

  const { meshRef } = useBrightenModel(animalBrightenPresets.aquatic);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmp1ac7fcj2ply.geometry}
        material={nodes.tmp1ac7fcj2ply.material}
        receiveShadow
        castShadow
      />
    </group>
  );
}

useGLTF.preload(alligatorGLB);
