/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/cerrado/blue-and-yellow-macaw.glb -t -o ./src/components/cerrado/blue-and-yellow-macaw.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import blueAndYellowMacawGlb from "@models/cerrado/blue-and-yellow-macaw.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpapge_0zgply: THREE.Mesh;
  };
  materials: object;
};

export function ModelBlueAndYellowMacaw(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(blueAndYellowMacawGlb) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpapge_0zgply.geometry}
        material={nodes.tmpapge_0zgply.material}
      />
    </group>
  );
}

useGLTF.preload(blueAndYellowMacawGlb);
