/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/iguana.glb -t -o ./src/components/caatinga/model-iguana.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    tmpgxolwgnyply: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/iguana.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tmpgxolwgnyply.geometry} material={nodes.tmpgxolwgnyply.material} />
    </group>
  )
}

useGLTF.preload('/iguana.glb')
