/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/cactus.glb -t -o ./src/components/caatinga/model-cactus.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BarrelCactus_mesh: THREE.Mesh
  }
  materials: {
    BarrelCactus_mat: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/cactus.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BarrelCactus_mesh.geometry} material={materials.BarrelCactus_mat} />
    </group>
  )
}

useGLTF.preload('/cactus.glb')
