/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/cerrado/giant-armadillo.glb -t -o ./src/components/cerrado/model-giant-armadillo.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import giantArmadilloGLB from "@models/cerrado/giant-armadillo.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpwwyiucc9ply: THREE.Mesh;
  };
  materials: object;
};

export function ModelGiantArmadillo(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(giantArmadilloGLB) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpwwyiucc9ply.geometry}
        material={nodes.tmpwwyiucc9ply.material}
      />
    </group>
  );
}

useGLTF.preload(giantArmadilloGLB);
