/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/armadillo.glb -t -o ./src/components/caatinga/model-armadillo.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import armadilloGlb from "@/assets/models/caatinga/armadillo.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpxvd_zn8nply: THREE.Mesh;
  };
  materials: object;
};

export function ModelArmadillo(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(armadilloGlb) as GLTFResult;

  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpxvd_zn8nply.geometry}
        material={nodes.tmpxvd_zn8nply.material}
      />
    </group>
  );
}

useGLTF.preload(armadilloGlb);
