/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/cactus.glb -t -o ./src/components/caatinga/model-cactus.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import cactusGlb from "@models/caatinga/cactus.glb";

type GLTFResult = GLTF & {
  nodes: {
    BarrelCactus_mesh: THREE.Mesh;
  };
  materials: {
    BarrelCactus_mat: THREE.MeshStandardMaterial;
  };
};

export function ModelCactus(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(cactusGlb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.BarrelCactus_mesh.geometry}
        material={materials.BarrelCactus_mat}
      />
    </group>
  );
}

useGLTF.preload(cactusGlb);
