/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/mata-atlantica/toucan.glb -t -o ./src/components/mata-atlantica/model-toucan.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import toucanGLB from "@models/mata-atlantica/toucan.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpr6d7jta7ply: THREE.Mesh;
  };
  materials: object;
};

export function ModelToucan(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(toucanGLB) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpr6d7jta7ply.geometry}
        material={nodes.tmpr6d7jta7ply.material}
      />
    </group>
  );
}

useGLTF.preload(toucanGLB);
