/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/animals/emu.glb -t -o ./src/components/atoms/animals/EmuModel.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import emu from "@models/animals/emu.glb";

type GLTFResult = GLTF & {
  nodes: {
    Geo_Emu: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
  };
};

export function EmuModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(emu) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geo_Emu.geometry} material={materials.lambert2SG} />
    </group>
  );
}

useGLTF.preload(emu);
