/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/iguana.glb -t -o ./src/components/caatinga/model-iguana.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import iguanaGlb from "@models/caatinga/iguana.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpgxolwgnyply: THREE.Mesh;
  };
  materials: object;
};

export function ModelIguana(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(iguanaGlb) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpgxolwgnyply.geometry}
        material={nodes.tmpgxolwgnyply.material}
      />
    </group>
  );
}

useGLTF.preload(iguanaGlb);
