/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/bush-stone.glb -o teste.tsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import bushStoneGlb from "@models/bush-stone.glb";

type GLTFResult = GLTF & {
  nodes: {
    rock_2_1: THREE.Mesh;
    rock_2_2: THREE.Mesh;
  };
  materials: {
    ["Herbs.001"]: THREE.MeshStandardMaterial;
    ["Rocks.001"]: THREE.MeshStandardMaterial;
  };
};

export const ModelBushStone = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(bushStoneGlb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={100}>
        <mesh
          geometry={nodes.rock_2_1.geometry}
          material={materials["Herbs.001"]}
        />
        <mesh
          geometry={nodes.rock_2_2.geometry}
          material={materials["Rocks.001"]}
        />
      </group>
    </group>
  );
};

useGLTF.preload(bushStoneGlb);
