/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/cactus-2.glb -t -o ./src/components/caatinga/model-cactus-2.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import cactus2Glb from "@models/caatinga/cactus-2.glb";

type GLTFResult = GLTF & {
  nodes: {
    cactus: THREE.Mesh;
  };
  materials: {
    None: THREE.MeshStandardMaterial;
  };
};

export function ModelCactus2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(cactus2Glb) as GLTFResult;

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cactus.geometry} material={materials.None} />
    </group>
  );
}

useGLTF.preload(cactus2Glb);
