/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ocean.glb -o ./src/components/Maps/components/Ocean -t 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import ocean from "@models/ocean.glb";

type GLTFResult = GLTF & {
  nodes: {
    Node: THREE.Mesh;
  };
  materials: {
    Mat: THREE.MeshStandardMaterial;
  };
};

export function Ocean(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(ocean) as GLTFResult;
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Node.geometry} material={materials.Mat} />
      </group>
    </RigidBody>
  );
}

useGLTF.preload(ocean);
