/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/cactus-4.glb -t -o ./src/components/caatinga/model-cactus-4.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import cactus4Glb from "@models/caatinga/cactus-4.glb";

type GLTFResult = GLTF & {
  nodes: {
    prickly_pear_cactus: THREE.Mesh;
  };
  materials: {
    None: THREE.MeshStandardMaterial;
  };
};

export function ModelCactus4(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(cactus4Glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.prickly_pear_cactus.geometry}
        material={materials.None}
      />
    </group>
  );
}

useGLTF.preload(cactus4Glb);
