/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/animals/want-want.glb -t -o ./src/components/ModelWantWant.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import wantWantGlb from "@models/pampa/want-want.glb";

type GLTFResult = GLTF & {
  nodes: {
    geometry_0: THREE.Mesh;
  };
  materials: {};
};

export function ModelWantWant(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(wantWantGlb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.geometry_0.geometry}
        material={nodes.geometry_0.material}
      />
    </group>
  );
}

useGLTF.preload(wantWantGlb);
