/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/animals/pampa/zorrilho.glb -t -o ./src/components/ModelZorrilho.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import zorrilhoGLB from "@models/pampa/zorrilho.glb";

type GLTFResult = GLTF & {
  nodes: {
    tmpi_6f6dtuply: THREE.Mesh;
  };
  materials: {};
};

export function ModelZorrilho(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(zorrilhoGLB) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tmpi_6f6dtuply.geometry}
        material={nodes.tmpi_6f6dtuply.material}
      />
    </group>
  );
}

useGLTF.preload(zorrilhoGLB);
