/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/dry-tree.glb -o teste.tsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Tree_branch: THREE.Mesh;
  };
  materials: {
    None: THREE.MeshStandardMaterial;
  };
};

export const DryTree = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/models/dry-tree.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tree_branch.geometry} material={materials.None} />
    </group>
  );
};

useGLTF.preload("/models/dry-tree.glb");
