/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/island-1.glb -o teste.tsx -r public 
*/

import {
  NAME_ISLAND,
  POSITIONS_ISLAND_DATA,
  SOIL_COLOR_ISLAND,
} from "@/lib/constants/island";
import islandModelPath from "@models/island-1.glb";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { useMemo } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    IslandLarge_1: THREE.Mesh;
    IslandLarge_2: THREE.Mesh;
  };
  materials: {
    dirt: THREE.MeshStandardMaterial;
    grass: THREE.MeshStandardMaterial;
  };
};

export const IslandSoilModel = ({
  islandName,
  ...props
}: JSX.IntrinsicElements["group"] & {
  islandName: (typeof NAME_ISLAND)[number];
}) => {
  const { nodes, materials: originalMaterials } = useGLTF(
    islandModelPath
  ) as GLTFResult;

  const color = SOIL_COLOR_ISLAND[islandName];
  const positionData = POSITIONS_ISLAND_DATA[islandName];

  const position = useMemo(() => {
    return new THREE.Vector3(positionData.x, positionData.y, positionData.z);
  }, [positionData]);

  const grassMaterial = useMemo(() => {
    const newMaterial = originalMaterials.grass.clone();
    newMaterial.color = new THREE.Color(color);
    newMaterial.roughness = 0.9;
    newMaterial.metalness = 0;
    return newMaterial;
  }, [originalMaterials.grass, color]);

  return (
    <RigidBody type="fixed" position={position} colliders="hull">
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={800}>
          <mesh
            geometry={nodes.IslandLarge_1.geometry}
            material={originalMaterials.dirt}
          />
          <mesh
            geometry={nodes.IslandLarge_2.geometry}
            material={grassMaterial}
          />
        </group>
      </group>
    </RigidBody>
  );
};

useGLTF.preload(islandModelPath);
