/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/rattlesnake.glb -t -o ./src/components/caatinga/model-rattlesnake.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import rattlesnakeGlb from "@models/caatinga/rattlesnake.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmp883gs79yply: THREE.Mesh;
  };
  materials: object;
};

export function ModelRattlesnake(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(rattlesnakeGlb) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmp883gs79yply.geometry}
        material={nodes.tmp883gs79yply.material}
      />
    </group>
  );
}

useGLTF.preload(rattlesnakeGlb);
