/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/mata-atlantica/golden-lion-tamarin.glb -t -o ./src/components/mata-atlantica/golden-lion-tamarin.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import goldenLionTamarinGLB from "@models/mata-atlantica/golden-lion-tamarin.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpbteot40vply: THREE.Mesh;
  };
  materials: object;
};

export function ModelGoldenLionTamarin(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(goldenLionTamarinGLB) as GLTFResult;

  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpbteot40vply.geometry}
        material={nodes.tmpbteot40vply.material}
      />
    </group>
  );
}

useGLTF.preload(goldenLionTamarinGLB);
