/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/mata-atlantica/tapir.glb -t -o ./src/components/mata-atlantica/model-tapir.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import tapirGLB from "@models/mata-atlantica/tapir.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpwcqjl8llply: THREE.Mesh;
  };
  materials: object;
};

export function ModelTapir(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(tapirGLB) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpwcqjl8llply.geometry}
        material={nodes.tmpwcqjl8llply.material}
      />
    </group>
  );
}

useGLTF.preload(tapirGLB);
