/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/animals/pampa/rhea.glb -t -o ./src/components/ModelRhea.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import rheaGLB from "@models/pampa/rhea.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmprp__qzsyply: THREE.Mesh;
  };
  materials: {};
};

export function ModelRhea(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(rheaGLB) as GLTFResult;

  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmprp__qzsyply.geometry}
        material={nodes.tmprp__qzsyply.material}
      />
    </group>
  );
}

useGLTF.preload(rheaGLB);
