/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/amazonia/parrot.glb -t -o ./src/components/amazonia/index.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import parrotGlb from "@models/amazonia/parrot.glb";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
    lambert3SG: THREE.MeshStandardMaterial;
  };
};

export function ModelParrot(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(parrotGlb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Node-Mesh"].geometry}
        material={materials.lambert2SG}
      />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.lambert3SG}
      />
    </group>
  );
}

useGLTF.preload(parrotGlb);
