/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/tree-2.glb -o teste.tsx -r public 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    mat20: THREE.MeshStandardMaterial;
    mat9: THREE.MeshStandardMaterial;
  };
};

export const Tree2 = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF("/models/tree-2.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat20} />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat9}
      />
    </group>
  );
};

useGLTF.preload("/models/tree-2.glb");
