/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/cerrado/anteater.glb -t -o ./src/components/cerrado/model-anteater.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import anteaterGLB from "@models/cerrado/anteater.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpimx_5469ply: THREE.Mesh;
  };
  materials: object;
};

export function ModelAnteater(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(anteaterGLB) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpimx_5469ply.geometry}
        material={nodes.tmpimx_5469ply.material}
      />
    </group>
  );
}

useGLTF.preload(anteaterGLB);
