/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/mata-atlantica/rufous-rumped-thrush.glb -t -o ./src/components/mata-atlantica/rufous-rumped-thrush.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import rufousRumpedThrushGLB from "@models/mata-atlantica/rufous-rumped-thrush.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpx7aa1c6eply: THREE.Mesh;
  };
  materials: object;
};

export function ModelRufousRumpedThrush(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(rufousRumpedThrushGLB) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpx7aa1c6eply.geometry}
        material={nodes.tmpx7aa1c6eply.material}
      />
    </group>
  );
}

useGLTF.preload(rufousRumpedThrushGLB);
