/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/black-caiman.glb -o ./src/components/Maps/components/BlackCaiman -t 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";

type GLTFResult = GLTF & {
  nodes: {
    BlackCaiman_mesh: THREE.Mesh;
  };
  materials: {
    BlackCaiman_mat: THREE.MeshStandardMaterial;
  };
};

export function BlackCaiman(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/black-caiman.glb") as GLTFResult;

  const brightMaterial = new THREE.MeshStandardMaterial({
    color: "#868779",
    roughness: 0.3,
    metalness: 0,
  });

  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.BlackCaiman_mesh.geometry}
          material={brightMaterial}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/models/black-caiman.glb");
