/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/amazonia/sloth.glb -t -o ./src/components/amazonia/index.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import slothGlb from "@models/amazonia/sloth.glb";
import {
  animalBrightenPresets,
  useBrightenModel,
} from "@/lib/hooks/use-brighten-model";

type GLTFResult = GLTF & {
  nodes: {
    tmpgbag34oeply: THREE.Mesh;
  };
  materials: {};
};

export function ModelSloth(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF(slothGlb) as GLTFResult;
  const { meshRef } = useBrightenModel(animalBrightenPresets.terrestrial);
  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        geometry={nodes.tmpgbag34oeply.geometry}
        material={nodes.tmpgbag34oeply.material}
      />
    </group>
  );
}

useGLTF.preload(slothGlb);
