/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/parrot.glb -o ./src/components/Maps/components/Parrot -t 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import parrot from "@models/parrot.glb";

type GLTFResult = GLTF & {
  nodes: {
    ["Node-Mesh"]: THREE.Mesh;
    ["Node-Mesh_1"]: THREE.Mesh;
  };
  materials: {
    lambert2SG: THREE.MeshStandardMaterial;
    lambert3SG: THREE.MeshStandardMaterial;
  };
};

export function Parrot(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(parrot) as GLTFResult;
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes["Node-Mesh"].geometry}
          material={materials.lambert2SG}
        />
        <mesh
          geometry={nodes["Node-Mesh_1"].geometry}
          material={materials.lambert3SG}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload(parrot);
