/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/animals/parrot-branch.glb -o ./src/components/Maps/components/ParrotBranch -t 
*/

import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ScarletMacaw_mesh: THREE.Mesh;
  };
  materials: {
    ScarletMacaw_mat: THREE.MeshStandardMaterial;
  };
};

export function ParrotBranch(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/animals/parrot-branch.glb"
  ) as GLTFResult;
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.ScarletMacaw_mesh.geometry}
          material={materials.ScarletMacaw_mat}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/models/animals/parrot-branch.glb");
