/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/flower.glb -t -o ./src/components/ModelFlower.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import flowerSrc from "@models/flower.glb";

type GLTFResult = GLTF & {
  nodes: {
    Flower_3_Group_1: THREE.Mesh;
    Flower_3_Group_2: THREE.Mesh;
  };
  materials: {
    Flowers: THREE.MeshStandardMaterial;
    Leaves: THREE.MeshStandardMaterial;
  };
};

export function ModelFlower(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(flowerSrc) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Flower_3_Group_1.geometry}
        material={materials.Flowers}
      />
      <mesh
        geometry={nodes.Flower_3_Group_2.geometry}
        material={materials.Leaves}
      />
    </group>
  );
}

useGLTF.preload(flowerSrc);
