/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/bush.glb -t -o ./src/components/Bush.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";
import bushSrc from "@models/bush.glb";

type GLTFResult = GLTF & {
  nodes: {
    Bush_Large: THREE.Mesh;
  };
  materials: {
    Texture_Leaves: THREE.MeshStandardMaterial;
  };
};

export function ModelBush(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(bushSrc) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Bush_Large.geometry}
        material={materials.Texture_Leaves}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload(bushSrc);
