/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/assets/models/caatinga/cactus-3.glb -t -o ./src/components/caatinga/model-cactus-3.tsx 
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

import cactus3Glb from "@models/caatinga/cactus-3.glb";

type GLTFResult = GLTF & {
  nodes: {
    OrganPipeCactus_Mesh: THREE.Mesh;
  };
  materials: {
    OrganPipeCactus_Mat: THREE.MeshStandardMaterial;
  };
};

export function ModelCactus3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(cactus3Glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.OrganPipeCactus_Mesh.geometry}
        material={materials.OrganPipeCactus_Mat}
      />
    </group>
  );
}

useGLTF.preload(cactus3Glb);
